const STORAGE_KEY="tabletten_medicines_v4",HISTORY_KEY="tabletten_history_v4",THEME_KEY="tabletten_theme";
const $=id=>document.getElementById(id);const el={name:$('name'),substance:$('substance'),strength:$('strength'),manufacturer:$('manufacturer'),barcode:$('barcode'),packSize:$('packSize'),stock:$('stock'),dailyDose:$('dailyDose'),reminderLimit:$('reminderLimit'),times:$('times'),photo:$('photo'),note:$('note'),color:$('color'),saveBtn:$('saveBtn'),cancelEditBtn:$('cancelEditBtn'),notifyBtn:$('notifyBtn'),checkBtn:$('checkBtn'),exportBtn:$('exportBtn'),importBtn:$('importBtn'),importFile:$('importFile'),copyShoppingBtn:$('copyShoppingBtn'),clearHistoryBtn:$('clearHistoryBtn'),darkModeBtn:$('darkModeBtn'),list:$('medicineList'),todayList:$('todayList'),shoppingList:$('shoppingList'),historyList:$('historyList'),countTotal:$('countTotal'),countDue:$('countDue'),countCritical:$('countCritical')};
let medicines=loadJson(STORAGE_KEY,[]),history=loadJson(HISTORY_KEY,[]),editId=null,editPhotoData="";
function loadJson(k,f){const r=localStorage.getItem(k);return r?JSON.parse(r):f}function saveAll(){localStorage.setItem(STORAGE_KEY,JSON.stringify(medicines));localStorage.setItem(HISTORY_KEY,JSON.stringify(history))}
if(localStorage.getItem(THEME_KEY)==="dark")document.body.classList.add("dark");function toggleDarkMode(){document.body.classList.toggle("dark");localStorage.setItem(THEME_KEY,document.body.classList.contains("dark")?"dark":"light")}
function todayKey(){return new Date().toISOString().slice(0,10)}function nowText(){return new Date().toLocaleString("de-DE",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"})}function formatDate(d){return d.toLocaleDateString("de-DE",{day:"2-digit",month:"2-digit",year:"numeric"})}
function parseTimes(v){return String(v||"").split(",").map(x=>x.trim()).filter(Boolean)}
function calc(m){const dose=Math.max(Number(m.dailyDose),.1),days=Math.floor(Number(m.stock)/dose),usable=Number(m.stock)-Number(m.reminderLimit),daysRem=usable<=0?0:Math.floor(usable/dose),empty=new Date(),rem=new Date();empty.setDate(empty.getDate()+days);rem.setDate(rem.getDate()+daysRem);return{daysRemaining:days,daysUntilReminder:daysRem,emptyDate:empty,reminderDate:rem}}
function status(m){const d=calc(m);if(Number(m.stock)<=Number(m.reminderLimit))return{className:"critical",label:"Sofort bestellen"};if(d.daysUntilReminder<=7)return{className:"warning",label:"Bald bestellen"};return{className:"ok",label:"Ausreichend"}}
function takenToday(id,time){return history.some(h=>h.medicineId===id&&h.dateKey===todayKey()&&h.time===time&&h.type==="taken")}function dueItems(){const items=[];medicines.forEach(m=>(m.times&&m.times.length?m.times:["Heute"]).forEach(t=>{if(!takenToday(m.id,t))items.push({medicine:m,time:t})}));return items}
function esc(t){return String(t).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}function escJs(t){return String(t).replace(/\\/g,"\\\\").replace(/'/g,"\\'")}
function renderAll(){renderMeds();renderToday();renderShopping();renderHistory()}
function renderToday(){const items=dueItems();el.countDue.textContent=items.length;if(!items.length){el.todayList.innerHTML='<div class="empty">Für heute ist alles als eingenommen markiert.</div>';return}el.todayList.innerHTML="";items.forEach(x=>{const m=x.medicine,d=document.createElement("div");d.className="today-item";d.innerHTML=`<div class="today-header"><h3>💊 ${esc(m.name)}</h3><span class="badge due">${esc(x.time)}</span></div><div class="info">${m.strength?`Stärke: <strong>${esc(m.strength)}</strong><br>`:""}Einnahme: <strong>${m.dailyDose} pro Tag</strong></div><button class="take" onclick="takeDose(${m.id}, '${escJs(x.time)}')">Eingenommen</button>`;el.todayList.appendChild(d)})}
function renderMeds(){el.list.innerHTML="";let crit=0;medicines.forEach(m=>{if(status(m).className==="critical")crit++});el.countTotal.textContent=medicines.length;el.countCritical.textContent=crit;if(!medicines.length){el.list.innerHTML='<div class="empty">Noch kein Medikament angelegt.</div>';return}medicines.slice().sort((a,b)=>calc(a).daysUntilReminder-calc(b).daysUntilReminder).forEach(m=>{const dta=calc(m),s=status(m),d=document.createElement("div");d.className=`medicine ${m.color||"blue"} ${s.className}`;d.innerHTML=`<div class="medicine-header"><h3>💊 ${esc(m.name)}</h3><span class="badge ${s.className}">${s.label}</span></div>${m.photoData?`<img class="med-photo" src="${m.photoData}" alt="Foto">`:""}<div class="info">${m.substance?`Wirkstoff: <strong>${esc(m.substance)}</strong><br>`:""}${m.strength?`Stärke: <strong>${esc(m.strength)}</strong><br>`:""}${m.manufacturer?`Hersteller: <strong>${esc(m.manufacturer)}</strong><br>`:""}${m.barcode?`PZN/Barcode: <strong>${esc(m.barcode)}</strong><br>`:""}Einnahmezeiten: <strong>${esc((m.times||[]).join(", ")||"nicht festgelegt")}</strong><br>Bestand: <strong>${m.stock} Stück</strong><br>Packungsgröße: <strong>${m.packSize} Stück</strong><br>Einnahme: <strong>${m.dailyDose} pro Tag</strong><br>Reicht noch: <strong>${dta.daysRemaining} Tage</strong><br>Nachbestellen ab: <strong>${formatDate(dta.reminderDate)}</strong><br>Voraussichtlich leer: <strong>${formatDate(dta.emptyDate)}</strong>${m.note?`<div class="note">Notiz: ${esc(m.note)}</div>`:""}</div><div class="action-grid"><button class="take" onclick="takeDose(${m.id}, 'manuell')">Jetzt eingenommen</button><button class="pack" onclick="addPack(${m.id})">Neue Packung erhalten</button><button class="edit" onclick="editMedicine(${m.id})">Bearbeiten</button><button class="delete" onclick="deleteMedicine(${m.id})">Löschen</button></div>`;el.list.appendChild(d)})}
function renderShopping(){const arr=medicines.filter(m=>status(m).className!=="ok");if(!arr.length){el.shoppingList.innerHTML="Aktuell muss nichts nachbestellt werden.";return}el.shoppingList.innerHTML=arr.map(m=>`• ${[m.name,m.substance,m.strength,m.manufacturer].filter(Boolean).map(esc).join(" – ")} | Bestand: ${m.stock} Stück | PZN: ${esc(m.barcode||"-")}`).join("<br>")}
function renderHistory(){const list=history.slice().reverse().slice(0,30);if(!list.length){el.historyList.innerHTML='<div class="empty">Noch keine Einträge im Protokoll.</div>';return}el.historyList.innerHTML="";list.forEach(h=>{const d=document.createElement("div");d.className="history-item";d.innerHTML=`<strong>${esc(h.medicineName)}</strong><br>${h.type==="taken"?"Eingenommen":"Neue Packung"} · ${esc(h.time||"-")}<br><span class="note">${esc(h.createdAt)}</span>`;el.historyList.appendChild(d)})}
function valid(v,min){return !Number.isNaN(v)&&v>=min}function readPhoto(){return new Promise(res=>{const f=el.photo.files&&el.photo.files[0];if(!f){res(editPhotoData||"");return}const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>res(editPhotoData||"");r.readAsDataURL(f)})}
async function saveForm(){const photoData=await readPhoto(),m={id:editId||Date.now(),name:el.name.value.trim(),substance:el.substance.value.trim(),strength:el.strength.value.trim(),manufacturer:el.manufacturer.value.trim(),barcode:el.barcode.value.trim(),packSize:Number(el.packSize.value),stock:Number(el.stock.value),dailyDose:Number(String(el.dailyDose.value).replace(",",".")),reminderLimit:Number(el.reminderLimit.value),times:parseTimes(el.times.value),photoData,note:el.note.value.trim(),color:el.color.value};if(!m.name||!valid(m.packSize,1)||!valid(m.stock,0)||!valid(m.dailyDose,.1)||!valid(m.reminderLimit,0)){alert("Bitte alle Pflichtfelder korrekt ausfüllen.");return}if(editId)medicines=medicines.map(x=>x.id===editId?m:x);else medicines.push(m);saveAll();clearForm();renderAll();checkReminders(false)}
function clearForm(){editId=null;editPhotoData="";[el.name,el.substance,el.strength,el.manufacturer,el.barcode,el.packSize,el.stock,el.times,el.note].forEach(x=>x.value="");el.dailyDose.value="1";el.reminderLimit.value="10";el.photo.value="";el.color.value="blue";el.saveBtn.textContent="Speichern";el.cancelEditBtn.classList.add("hidden")}
function editMedicine(id){const m=medicines.find(x=>x.id===id);if(!m)return;editId=id;editPhotoData=m.photoData||"";el.name.value=m.name||"";el.substance.value=m.substance||"";el.strength.value=m.strength||"";el.manufacturer.value=m.manufacturer||"";el.barcode.value=m.barcode||"";el.packSize.value=m.packSize||"";el.stock.value=m.stock||"";el.dailyDose.value=m.dailyDose||"1";el.reminderLimit.value=m.reminderLimit||"10";el.times.value=(m.times||[]).join(", ");el.note.value=m.note||"";el.color.value=m.color||"blue";el.saveBtn.textContent="Änderung speichern";el.cancelEditBtn.classList.remove("hidden");scrollTo({top:0,behavior:"smooth"})}
function deleteMedicine(id){if(!confirm("Medikament wirklich löschen?"))return;medicines=medicines.filter(m=>m.id!==id);saveAll();renderAll()}function takeDose(id,time){const m=medicines.find(x=>x.id===id);if(!m)return;m.stock=Math.max(0,Number(m.stock)-Number(m.dailyDose));history.push({id:Date.now(),medicineId:m.id,medicineName:m.name,type:"taken",time,dateKey:todayKey(),createdAt:nowText()});saveAll();renderAll();checkReminders(false)}function addPack(id){const m=medicines.find(x=>x.id===id);if(!m)return;m.stock=Number(m.stock)+Number(m.packSize);history.push({id:Date.now(),medicineId:m.id,medicineName:m.name,type:"pack",time:"Packung",dateKey:todayKey(),createdAt:nowText()});saveAll();renderAll()}
async function enableNotifications(){if(!("Notification"in window)){alert("Dieser Browser unterstützt keine Benachrichtigungen.");return}const p=await Notification.requestPermission();alert(p==="granted"?"Benachrichtigungen sind aktiviert.":"Benachrichtigungen wurden nicht erlaubt.");if(p==="granted")checkReminders(false)}
function checkReminders(show=true){const crit=medicines.filter(m=>status(m).className==="critical"),due=dueItems();if(!crit.length&&!due.length){if(show)alert("Alles in Ordnung. Keine kritischen Bestände und keine offenen Einnahmen.");return}const msg=[];if(due.length)msg.push("Offene Einnahmen: "+due.map(x=>`${x.medicine.name} ${x.time}`).join(", "));if(crit.length)msg.push("Nachbestellen: "+crit.map(m=>m.name).join(", "));if("Notification"in window&&Notification.permission==="granted")new Notification("Tabletten Erinnerung",{body:msg.join(" | ")});if(show)alert(msg.join("\n\n"))}
function exportBackup(){const backup={app:"Tabletten Erinnerung",version:4,exportedAt:new Date().toISOString(),medicines,history},blob=new Blob([JSON.stringify(backup,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="tabletten-backup-v4.json";a.click();URL.revokeObjectURL(url)}
function importBackup(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.medicines))throw Error();medicines=d.medicines;history=Array.isArray(d.history)?d.history:[];saveAll();renderAll();alert("Backup wurde importiert.")}catch{alert("Backup konnte nicht gelesen werden.")}};r.readAsText(file)}
function shoppingText(){const arr=medicines.filter(m=>status(m).className!=="ok");return arr.length?"Nachbestellliste:\n"+arr.map(m=>`- ${m.name}${m.substance?" / "+m.substance:""}${m.strength?" / "+m.strength:""}${m.manufacturer?" / "+m.manufacturer:""} | PZN: ${m.barcode||"-"} | Bestand: ${m.stock} Stück`).join("\n"):"Aktuell muss nichts nachbestellt werden."}
async function copyShopping(){const t=shoppingText();try{await navigator.clipboard.writeText(t);alert("Nachbestellliste wurde kopiert.")}catch{alert(t)}}function clearHistory(){if(!confirm("Protokoll wirklich löschen?"))return;history=[];saveAll();renderAll()}
el.saveBtn.onclick=saveForm;el.cancelEditBtn.onclick=clearForm;el.notifyBtn.onclick=enableNotifications;el.checkBtn.onclick=()=>checkReminders(true);el.exportBtn.onclick=exportBackup;el.importBtn.onclick=()=>el.importFile.click();el.importFile.onchange=e=>{if(e.target.files[0])importBackup(e.target.files[0])};el.copyShoppingBtn.onclick=copyShopping;el.clearHistoryBtn.onclick=clearHistory;el.darkModeBtn.onclick=toggleDarkMode;if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js");renderAll();setTimeout(()=>checkReminders(false),800);
